language: R
sudo: false
cache: packages

r: bioc-release

r-packages:
  - data.table
  - ggplot2

bioc_packages:
  - Biostrings
  - GenomicAlignments
  - GenomicFeatures
  - GenomicRanges
  - IRanges

notifications:
  email:
    on_success: never
    on_failure: never
    
warnings_are_errors: false
